// Shared pSEO data — single source of truth for services and cities
// Imported by both page.tsx and sitemap.ts

export const SERVICES: Record<string, { label: string; description: string; slug: string }> = {
  "tarot-reading": {
    label: "Tarot Reading",
    description: "Classic Rider-Waite deck with intuitive guidance for insight and direction.",
    slug: "tarot-reading",
  },
  "astrology-reading": {
    label: "Astrology Reading",
    description: "Full natal chart analysis with Solar Fire software for precision.",
    slug: "astrology-reading",
  },
  "lenormand-reading": {
    label: "Lenormand Reading",
    description: "Precise, grounded predictions using the 36-card Lenormand deck.",
    slug: "lenormand-reading",
  },
  "oracle-reading": {
    label: "Oracle Reading",
    description: "Intuitive guidance through beautifully illustrated oracle decks.",
    slug: "oracle-reading",
  },
  "channeling-session": {
    label: "Channeling Session",
    description: "Connect with spirit guides and loved ones for healing messages.",
    slug: "channeling-session",
  },
  "executive-tarot-advising": {
    label: "Executive Tarot Advising",
    description: "Strategic decision-making support for executives and business owners.",
    slug: "executive-tarot-advising",
  },
  "intuitive-business-consulting": {
    label: "Intuitive Business Consulting",
    description: "Business strategy guided by intuition and archetypal wisdom.",
    slug: "intuitive-business-consulting",
  },
  "private-tarot-reading": {
    label: "Private Tarot Reading",
    description: "Intimate, deep-dive sessions for personal transformation.",
    slug: "private-tarot-reading",
  },
  "psychic-life-coaching": {
    label: "Psychic Life Coaching",
    description: "Combine psychic guidance with practical life coaching for transformation.",
    slug: "psychic-life-coaching",
  },
  "spiritual-counseling": {
    label: "Spiritual Counseling",
    description: "Compassionate guidance for spiritual growth and emotional healing.",
    slug: "spiritual-counseling",
  },
};

export const CITIES: Record<string, { city: string; state: string; metro: string }> = {
  "albuquerque-nm": { city: "Albuquerque", state: "NM", metro: "915K metro area" },
  "arlington-tx": { city: "Arlington", state: "TX", metro: "4.2M Dallas-Fort Worth metro" },
  "aspen": { city: "Aspen", state: "CO", metro: "10K mountain community" },
  "atlanta-ga": { city: "Atlanta", state: "GA", metro: "6M metro area" },
  "austin-tx": { city: "Austin", state: "TX", metro: "2.2M metro area" },
  "baltimore-md": { city: "Baltimore", state: "MD", metro: "2.8M metro area" },
  "beverly-hills": { city: "Beverly Hills", state: "CA", metro: "34K exclusive enclave" },
  "boston-ma": { city: "Boston", state: "MA", metro: "4.9M metro area" },
  "charlotte-nc": { city: "Charlotte", state: "NC", metro: "2.7M metro area" },
  "chattanooga-tn": { city: "Chattanooga", state: "TN", metro: "500K metro area" },
  "chicago-il": { city: "Chicago", state: "IL", metro: "9.5M metro area" },
  "cleveland-oh": { city: "Cleveland", state: "OH", metro: "2M metro area" },
  "colorado-springs-co": { city: "Colorado Springs", state: "CO", metro: "760K metro area" },
  "columbus-oh": { city: "Columbus", state: "OH", metro: "2.1M metro area" },
  "dallas-tx": { city: "Dallas", state: "TX", metro: "7.5M metro area" },
  "denver-co": { city: "Denver", state: "CO", metro: "3M metro area" },
  "el-paso-tx": { city: "El Paso", state: "TX", metro: "868K metro area" },
  "fort-worth-tx": { city: "Fort Worth", state: "TX", metro: "4.2M Dallas-Fort Worth metro" },
  "fresno-ca": { city: "Fresno", state: "CA", metro: "1M metro area" },
  "greenwich": { city: "Greenwich", state: "CT", metro: "63K affluent suburb" },
  "houston-tx": { city: "Houston", state: "TX", metro: "7.2M metro area" },
  "indianapolis-in": { city: "Indianapolis", state: "IN", metro: "2.1M metro area" },
  "jackson-hole": { city: "Jackson Hole", state: "WY", metro: "35K mountain valley" },
  "jacksonville-fl": { city: "Jacksonville", state: "FL", metro: "1.6M metro area" },
  "kansas-city-mo": { city: "Kansas City", state: "MO", metro: "2.2M metro area" },
  "las-vegas-nv": { city: "Las Vegas", state: "NV", metro: "2.3M metro area" },
  "long-beach-ca": { city: "Long Beach", state: "CA", metro: "13M Los Angeles metro" },
  "los-angeles-ca": { city: "Los Angeles", state: "CA", metro: "13M metro area" },
  "louisville-ky": { city: "Louisville", state: "KY", metro: "1.3M metro area" },
  "malibu": { city: "Malibu", state: "CA", metro: "13M Los Angeles metro" },
  "memphis-tn": { city: "Memphis", state: "TN", metro: "1.3M metro area" },
  "mesa-az": { city: "Mesa", state: "AZ", metro: "5.1M Phoenix metro" },
  "miami-fl": { city: "Miami", state: "FL", metro: "6.2M metro area" },
  "milwaukee-wi": { city: "Milwaukee", state: "WI", metro: "1.7M metro area" },
  "minneapolis-mn": { city: "Minneapolis", state: "MN", metro: "3.7M metro area" },
  "nashville-tn": { city: "Nashville", state: "TN", metro: "2.1M metro area" },
  "new-orleans-la": { city: "New Orleans", state: "LA", metro: "1.3M metro area" },
  "new-york-ny": { city: "New York", state: "NY", metro: "20M metro area" },
  "oakland-ca": { city: "Oakland", state: "CA", metro: "7.8M San Francisco Bay Area" },
  "oklahoma-city-ok": { city: "Oklahoma City", state: "OK", metro: "1.4M metro area" },
  "omaha-ne": { city: "Omaha", state: "NE", metro: "944K metro area" },
  "palm-beach": { city: "Palm Beach", state: "FL", metro: "1.5M South Florida" },
  "philadelphia-pa": { city: "Philadelphia", state: "PA", metro: "6.2M metro area" },
  "phoenix-az": { city: "Phoenix", state: "AZ", metro: "5.1M metro area" },
  "portland-or": { city: "Portland", state: "OR", metro: "2.5M metro area" },
  "raleigh-nc": { city: "Raleigh", state: "NC", metro: "1.4M metro area" },
  "sacramento-ca": { city: "Sacramento", state: "CA", metro: "2.4M metro area" },
  "san-antonio-tx": { city: "San Antonio", state: "TX", metro: "2.5M metro area" },
  "san-diego-ca": { city: "San Diego", state: "CA", metro: "3.3M metro area" },
  "san-francisco-ca": { city: "San Francisco", state: "CA", metro: "7.8M Bay Area metro" },
  "santa-monica": { city: "Santa Monica", state: "CA", metro: "13M Los Angeles metro" },
  "scarsdale": { city: "Scarsdale", state: "NY", metro: "18K affluent suburb" },
  "seattle-wa": { city: "Seattle", state: "WA", metro: "4M metro area" },
  "tampa-fl": { city: "Tampa", state: "FL", metro: "3.3M metro area" },
  "tucson-az": { city: "Tucson", state: "AZ", metro: "1M metro area" },
  "tulsa-ok": { city: "Tulsa", state: "OK", metro: "1M metro area" },
  "virginia-beach-va": { city: "Virginia Beach", state: "VA", metro: "1.8M Hampton Roads" },
  "washington-dc": { city: "Washington", state: "DC", metro: "6.3M metro area" },
  "wichita-ks": { city: "Wichita", state: "KS", metro: "645K metro area" },
};
